kernel: fix build with GCC 7.x
drivers/net/ethernet/msm: Fix compile error
In file included from drivers/net/ethernet/msm/rndis_ipa_trace.h:81:0,
                 from drivers/net/ethernet/msm/rndis_ipa.c:32:
include/trace/define_trace.h:83:43: fatal error: ./rndis_ipa_trace.h: No such file or directory
                                           ^

drivers/platform/msm/ipa/ipa_v2: Fix compile error

In file included from drivers/platform/msm/ipa/ipa_v2/ipa_trace.h:135:0,
                 from drivers/platform/msm/ipa/ipa_v2/ipa.c:41:
include/trace/define_trace.h:83:43: fatal error: ./ipa_trace.h: No such file or directory
                                           ^

build: fix standalone compiling

Change-Id: I6f82cda3e00d1ecff0b20dcff36ca0ab3e3c5507
Signed-off-by: Francisco Franco <franciscofranco.1990@gmail.com>

drivers: fix compile error

# Conflicts:
#	drivers/input/misc/vl53L0/inc/stmvl53l0-cci.h
#	drivers/input/misc/vl53L0/inc/stmvl53l0-i2c.h
#	drivers/input/misc/vl53L0/inc/stmvl53l0.h
#	drivers/staging/prima/CORE/VOSS/src/wlan_nv_template_builtin.c